name: CS Creative and Customs
favicon: null
layout_spectrum: 0.5052
typography_spectrum: 0.10823
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
navigation:
  - name: SOUL
    id: c0a8db94-88c1-428c-bbbe-ea79d87c9460
    type: content
  - name: SOLID
    id: 3e52f08b-f4ad-4dd3-80fa-9041dba41842
    type: content
  - name: STRUCTURE
    id: 4b79a561-0afb-4629-a32d-c9f1befce4c2
    type: content
  - name: FLUID
    id: 3cd3eb59-959e-4251-9935-2e1d53f4fac6
    type: content
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 1
  lightness: 0
  saturation: 0.5030334
  rhythmicContrast: 0.25
purpose: []
